# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Set environment variables
ENV MLFLOW_TRACKING_URI="https://dagshub.com/<owner>/<repo>.mlflow"
ENV MODEL_NAME="fake"
ENV MODEL_VERSION="13"
ENV PORT=5000

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev
# move all the project
COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Serve the model
CMD mlflow models serve \
  --model-uri "models:/${MODEL_NAME}/${MODEL_VERSION}" \
  --no-conda \
  --port ${PORT}

# Expose the port
EXPOSE ${PORT}
