stages:
  train_titanic:
    cmd: .\.venv\Scripts\python.exe trainer.py
    deps:
      - src/pipeline.py
      - src/logger.py
      - trainer.py
      - conf/config.yaml
      - conf/pipeline/titanic_baseline.yaml
      - conf/pipeline/titanic_alt.yaml
      - data/raw/titanic/train.csv
      - data/raw/titanic/test.csv
    metrics:
      - reports/titanic/training_report.json:
          cache: false
    outs:
      - models/titanic/titanic_pipeline.pkl

  score_titanic:
    cmd: .\.venv\Scripts\python.exe src/training/evaluate.py --model-path models/titanic/titanic_pipeline.pkl --data-path data/raw/titanic/train.csv --predictions-path reports/titanic/downstream_predictions.csv --report-path reports/titanic/downstream_report.json --target-column Survived --drop-columns PassengerId
    deps:
      - src/training/evaluate.py
      - src/logger.py
      - models/titanic/titanic_pipeline.pkl
      - data/raw/titanic/train.csv
    metrics:
      - reports/titanic/downstream_report.json:
          cache: false
    outs:
      - reports/titanic/downstream_predictions.csv
